code --install-extension almenon.arepl --force &
code --install-extension BRBoer.vsc-conceal --force &
code --install-extension bungcip.better-toml --force &
code --install-extension christian-kohler.path-intellisense --force &
code --install-extension codezombiech.gitignore --force &
code --install-extension DavidAnson.vscode-markdownlint --force &
code --install-extension eamodio.gitlens --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension ExodiusStudios.comment-anchors --force &
code --install-extension GitHub.copilot --force &
code --install-extension IBM.output-colorizer --force &
code --install-extension James-Yu.latex-workshop --force &
code --install-extension johnpapa.vscode-peacock --force &
code --install-extension magicstack.MagicPython --force &
code --install-extension mikestead.dotenv --force &
code --install-extension monokai.theme-monokai-pro-vscode --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-vscode-remote.remote-containers --force &
code --install-extension ms-vscode-remote.remote-ssh --force &
code --install-extension ms-vscode-remote.remote-ssh-edit --force &
code --install-extension mushan.vscode-paste-image --force &
code --install-extension njpwerner.autodocstring --force &
code --install-extension OrangeX4.hsnips --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension ronnidc.nunjucks --force &
code --install-extension rpinski.shebang-snippets --force &
code --install-extension shakram02.bash-beautify --force &
code --install-extension Shan.code-settings-sync --force &
code --install-extension streetsidesoftware.code-spell-checker --force &
code --install-extension VisualStudioExptTeam.vscodeintellicode --force &
code --install-extension wholroyd.jinja --force &
code --install-extension yzhang.markdown-all-in-one --force
