version: 3

output: prefixed

vars:
  # colors
  GREEN: $(tput setaf 2)
  RED: $(tput setaf 1)
  BLUE: $(tput setaf 31)
  NC: $(tput sgr0)

  # Paths
  SELF_DIR: $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  CHEZMOIROOT: "{{.SELF_DIR}}/$(cat .chezmoiroot)"
  BREWFILE_PATH: "{{.CHEZMOIROOT}}/dot_core/brew/Brewfile"
  POETRY_PATH: "{{.HOME}}/.core/poetry"
  ZSH_CUSTOM_PATH: "{{.HOME}}/.core/zsh"
  SCRIPTS_PATH: "{{.CHEZMOIROOT}}/dot_core/scripts"

  # PYTHON
  PYTHON_BASE_VERSION: "3.9.10"
  PYTHON_BASE_ENV: "base"

  # custom packages to install first through brew
  BREW_CORE_INSTALLS: |-
    python@3.9
    cmake
    pyenv
    pyenv-virtualenv

tasks:
  "init":
    - task: "brew-tap"
    - task: "brew-core-install"
    - task: "oh-my-zsh-init"
    - task: "pyenv-base-env"
    - task: "brew-formula-install"

  "brew-tap":
    desc: "Install brew taps"
    cmds:
      - |
        while IFS= read -r line; do
            echo "Tapping $line"
            brew tap $line
            echo "Done Tapping $line"
        done < <(printf '%s\n' $(cat {{.BREWFILE_PATH}} |  grep '^[tap]' | grep -o '".*"' | tr -d '"' ))
      - echo 'DONE'

  "brew-core-install":
    desc: "Install brew core packages defined in BREW_CORE_INSTALLS variable"
    cmds:
      - |
        while IFS= read -r line; do
            echo "Installing $line"
            brew install $line
            echo "Done Installing $line"
        done < <(printf '%s\n' "{{.BREW_CORE_INSTALLS}}")

  "brew-formula-install":
    desc: "Install brew formulas defined on the Brewfile"
    cmds:
      - cat {{.BREWFILE_PATH}} | grep '^[brew]' | grep -o '".*"' | tr -d '"' | tr '\n' '\0' |   xargs -n 1 -0 -I@ bash -c "echo '{{.BLUE}} Installing @ {{.NC}}' && brew install @ && echo '{{.GREEN}} Done Installing @ {{.NC}}'"

  "oh-my-zsh-init":
    desc: "Initialize oh-my-zsh"
    cmds:
      - |
        if [ ! -d "{{.HOME}}/.oh-my-zsh" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        fi

  "pyenv-base-env":
    desc: "Create base python env for local machine through pyenv"
    cmds:
      - |
        echo "{{.BLUE}} Creating pyenv base env {{.NC}}"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        pyenv install {{.PYTHON_BASE_VERSION}}
        pyenv virtualenv {{.PYTHON_BASE_VERSION}} {{.PYTHON_BASE_ENV}}
        pyenv global {{.PYTHON_BASE_ENV}}
        pyenv rehash

  "poetry-init":
    desc: "Initialize poetry"
    cmds:
      - |
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        echo "$(ls $(pyenv root)/{{.PYTHON_BASE_ENV}}/versions/bin/python)"
