#!/usr/bin/env zsh
PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin"

# load environmental variables
source ${HOME}/.core/zsh/_paths.zsh

crontab -l >${HOME}/.core/scripts/crontab.save

chezmoi add ${HOME}/.core/scripts/crontab.save

echo "crontab saved as ${HOME}/.core/scripts/crontab.save"
