code --install-extension adpyke.vscode-sql-formatter --force &
code --install-extension adrianwilczynski.toggle-hidden --force &
code --install-extension akamud.vscode-theme-onedark --force &
code --install-extension alefragnani.Bookmarks --force &
code --install-extension alefragnani.project-manager --force &
code --install-extension analytic-signal.snippets-plotly --force &
code --install-extension batisteo.vscode-django --force &
code --install-extension bbenoist.Nix --force &
code --install-extension be5invis.toml --force &
code --install-extension bradlc.vscode-tailwindcss --force &
code --install-extension BRBoer.vsc-conceal --force &
code --install-extension burkeholland.simple-react-snippets --force &
code --install-extension castwide.solargraph --force &
code --install-extension Catppuccin.catppuccin-vsc --force &
code --install-extension charliermarsh.ruff --force &
code --install-extension ChrisChinchilla.vscode-pandoc --force &
code --install-extension christian-kohler.path-intellisense --force &
code --install-extension codezombiech.gitignore --force &
code --install-extension dannymcgee.vscode-go-grammar --force &
code --install-extension Dart-Code.dart-code --force &
code --install-extension DavidAnson.vscode-markdownlint --force &
code --install-extension dbaeumer.vscode-eslint --force &
code --install-extension dkundel.vscode-new-file --force &
code --install-extension donjayamanne.python-environment-manager --force &
code --install-extension DotJoshJohnson.xml --force &
code --install-extension dsznajder.es7-react-js-snippets --force &
code --install-extension dustypomerleau.rust-syntax --force &
code --install-extension eamodio.gitlens --force &
code --install-extension EditorConfig.EditorConfig --force &
code --install-extension enkia.tokyo-night --force &
code --install-extension Equinusocio.vsc-community-material-theme --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension evan-buss.font-switcher --force &
code --install-extension ExecutableBookProject.myst-highlight --force &
code --install-extension exercism.exercism-cli --force &
code --install-extension fabiospampinato.vscode-diff --force &
code --install-extension formulahendry.code-runner --force &
code --install-extension foxundermoon.shell-format --force &
code --install-extension GitHub.copilot --force &
code --install-extension GitHub.copilot-chat --force &
code --install-extension GitHub.copilot-labs --force &
code --install-extension GitHub.github-vscode-theme --force &
code --install-extension GitHub.remotehub --force &
code --install-extension github.vscode-github-actions --force &
code --install-extension GitHub.vscode-pull-request-github --force &
code --install-extension gitpod.gitpod-desktop --force &
code --install-extension gnramsay.create-python-module --force &
code --install-extension golang.go --force &
code --install-extension GrapeCity.gc-excelviewer --force &
code --install-extension Gruntfuggly.todo-tree --force &
code --install-extension hbenl.vscode-test-explorer --force &
code --install-extension humao.rest-client --force &
code --install-extension hzgood.dart-data-class-generator --force &
code --install-extension IBM.output-colorizer --force &
code --install-extension James-Yu.latex-workshop --force &
code --install-extension JannisX11.batch-rename-extension --force &
code --install-extension johnpapa.vscode-peacock --force &
code --install-extension JScearcy.rust-doc-viewer --force &
code --install-extension kakumei.ts-debug --force &
code --install-extension KevinRose.vsc-python-indent --force &
code --install-extension knowsuchagency.pdm-task-provider --force &
code --install-extension LeetCode.vscode-leetcode --force &
code --install-extension mads-hartmann.bash-ide-vscode --force &
code --install-extension magicstack.MagicPython --force &
code --install-extension mathematic.vscode-latex --force &
code --install-extension mgesbert.python-path --force &
code --install-extension mikestead.dotenv --force &
code --install-extension mkhl.shfmt --force &
code --install-extension monokai.theme-monokai-pro-vscode --force &
code --install-extension monosans.djlint --force &
code --install-extension ms-azuretools.azure-dev --force &
code --install-extension ms-azuretools.vscode-bicep --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force &
code --install-extension ms-python.black-formatter --force &
code --install-extension ms-python.gather --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.datawrangler --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force &
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force &
code --install-extension ms-vscode-remote.remote-containers --force &
code --install-extension ms-vscode-remote.remote-ssh --force &
code --install-extension ms-vscode-remote.remote-ssh-edit --force &
code --install-extension ms-vscode.azure-repos --force &
code --install-extension ms-vscode.azurecli --force &
code --install-extension ms-vscode.hexeditor --force &
code --install-extension ms-vscode.makefile-tools --force &
code --install-extension ms-vscode.remote-explorer --force &
code --install-extension ms-vscode.remote-repositories --force &
code --install-extension ms-vscode.test-adapter-converter --force &
code --install-extension ms-vscode.vscode-github-issue-notebooks --force &
code --install-extension ms-vscode.wordcount --force &
code --install-extension mtxr.sqltools --force &
code --install-extension mtxr.sqltools-driver-pg --force &
code --install-extension mushan.vscode-paste-image --force &
code --install-extension naumovs.color-highlight --force &
code --install-extension ninoseki.vscode-pylens --force &
code --install-extension njqdev.vscode-python-typehint --force &
code --install-extension OrangeX4.hsnips --force &
code --install-extension panicbit.cargo --force &
code --install-extension paulvarache.vscode-taskfile --force &
code --install-extension plibither8.remove-comments --force &
code --install-extension qufiwefefwoyn.inline-sql-syntax --force &
code --install-extension rebornix.ruby --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension REditorSupport.r --force &
code --install-extension richie5um2.vscode-sort-json --force &
code --install-extension ritwickdey.LiveServer --force &
code --install-extension rogalmic.bash-debug --force &
code --install-extension rust-lang.rust-analyzer --force &
code --install-extension ryuta46.multi-command --force &
code --install-extension sdras.night-owl --force &
code --install-extension serayuzgur.crates --force &
code --install-extension shd101wyy.markdown-preview-enhanced --force &
code --install-extension Siris01.catppuccin-theme --force &
code --install-extension sleistner.vscode-fileutils --force &
code --install-extension Stepsize.stepsize --force &
code --install-extension Swellaby.rust-pack --force &
code --install-extension Swellaby.vscode-rust-test-adapter --force &
code --install-extension tamasfe.even-better-toml --force &
code --install-extension teabyii.ayu --force &
code --install-extension tecosaur.latex-utilities --force &
code --install-extension TianyiShi.rmarkdown --force &
code --install-extension timonwong.shellcheck --force &
code --install-extension tintinweb.graphviz-interactive-preview --force &
code --install-extension truman.autocomplate-shell --force &
code --install-extension twixes.pypi-assistant --force &
code --install-extension usernamehw.errorlens --force &
code --install-extension vadimcn.vscode-lldb --force &
code --install-extension vintharas.learn-vim --force &
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples --force &
code --install-extension VisualStudioExptTeam.vscodeintellicode --force &
code --install-extension vivaxy.vscode-conventional-commits --force &
code --install-extension vscjava.vscode-gradle --force &
code --install-extension vscode-icons-team.vscode-icons --force &
code --install-extension vscodevim.vim --force &
code --install-extension wholroyd.jinja --force &
code --install-extension wingrunr21.vscode-ruby --force &
code --install-extension withfig.fig --force &
code --install-extension yzhang.markdown-all-in-one --force &
code --install-extension Zerotaskx.rust-extension-pack --force &
code --install-extension zhuangtongfa.material-theme --force &
code --install-extension ZneuRay.erb-vscode-snippets --force
