code --install-extension adpyke.vscode-sql-formatter --force &
code --install-extension albert.TabOut --force &
code --install-extension alefragnani.Bookmarks --force &
code --install-extension alefragnani.project-manager --force &
code --install-extension analytic-signal.snippets-plotly --force &
code --install-extension batisteo.vscode-django --force &
code --install-extension bbenoist.Nix --force &
code --install-extension be5invis.toml --force &
code --install-extension BRBoer.vsc-conceal --force &
code --install-extension bungcip.better-toml --force &
code --install-extension christian-kohler.path-intellisense --force &
code --install-extension codezombiech.gitignore --force &
code --install-extension DavidAnson.vscode-markdownlint --force &
code --install-extension donjayamanne.python-environment-manager --force &
code --install-extension DougFinke.vscode-pandoc --force &
code --install-extension dustypomerleau.rust-syntax --force &
code --install-extension eamodio.gitlens --force &
code --install-extension Equinusocio.vsc-community-material-theme --force &
code --install-extension Equinusocio.vsc-material-theme --force &
code --install-extension equinusocio.vsc-material-theme-icons --force &
code --install-extension esbenp.prettier-vscode --force &
code --install-extension evan-buss.font-switcher --force &
code --install-extension ExecutableBookProject.myst-highlight --force &
code --install-extension fabiospampinato.vscode-diff --force &
code --install-extension fehey.brackets-light-pro --force &
code --install-extension formulahendry.code-runner --force &
code --install-extension foxundermoon.shell-format --force &
code --install-extension GitHub.copilot-labs --force &
code --install-extension GitHub.copilot-nightly --force &
code --install-extension GitHub.github-vscode-theme --force &
code --install-extension GitHub.remotehub --force &
code --install-extension GitHub.vscode-pull-request-github --force &
code --install-extension gitpod.gitpod-desktop --force &
code --install-extension gnramsay.create-python-module --force &
code --install-extension golang.go --force &
code --install-extension GrapeCity.gc-excelviewer --force &
code --install-extension Gruntfuggly.todo-tree --force &
code --install-extension GulajavaMinistudio.mayukaithemevsc --force &
code --install-extension IBM.output-colorizer --force &
code --install-extension James-Yu.latex-workshop --force &
code --install-extension johnpapa.vscode-peacock --force &
code --install-extension KevinRose.vsc-python-indent --force &
code --install-extension knowsuchagency.pdm-task-provider --force &
code --install-extension mads-hartmann.bash-ide-vscode --force &
code --install-extension magicstack.MagicPython --force &
code --install-extension matangover.mypy --force &
code --install-extension mgesbert.python-path --force &
code --install-extension mikestead.dotenv --force &
code --install-extension monokai.theme-monokai-pro-vscode --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-python.black-formatter --force &
code --install-extension ms-python.gather --force &
code --install-extension ms-python.isort --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-vscode-remote.remote-containers --force &
code --install-extension ms-vscode-remote.remote-ssh --force &
code --install-extension ms-vscode-remote.remote-ssh-edit --force &
code --install-extension ms-vscode.azure-account --force &
code --install-extension ms-vscode.makefile-tools --force &
code --install-extension ms-vscode.remote-repositories --force &
code --install-extension ms-vscode.vscode-github-issue-notebooks --force &
code --install-extension ms-vscode.wordcount --force &
code --install-extension mushan.vscode-paste-image --force &
code --install-extension naumovs.color-highlight --force &
code --install-extension ninoseki.vscode-pylens --force &
code --install-extension njpwerner.autodocstring --force &
code --install-extension njqdev.vscode-python-typehint --force &
code --install-extension Okteto.remote-kubernetes --force &
code --install-extension OrangeX4.hsnips --force &
code --install-extension paulvarache.vscode-taskfile --force &
code --install-extension PKief.material-icon-theme --force &
code --install-extension qufiwefefwoyn.inline-sql-syntax --force &
code --install-extension redhat.vscode-yaml --force &
code --install-extension richie5um2.vscode-sort-json --force &
code --install-extension rogalmic.bash-debug --force &
code --install-extension ronnidc.nunjucks --force &
code --install-extension rust-lang.rust-analyzer --force &
code --install-extension sdras.night-owl --force &
code --install-extension shakram02.bash-beautify --force &
code --install-extension shd101wyy.markdown-preview-enhanced --force &
code --install-extension sleistner.vscode-fileutils --force &
code --install-extension tamasfe.even-better-toml --force &
code --install-extension teabyii.ayu --force &
code --install-extension timonwong.shellcheck --force &
code --install-extension truman.autocomplate-shell --force &
code --install-extension trunk.io --force &
code --install-extension vadimcn.vscode-lldb --force &
code --install-extension vintharas.learn-vim --force &
code --install-extension VisualStudioExptTeam.vscodeintellicode --force &
code --install-extension vivaxy.vscode-conventional-commits --force &
code --install-extension vscodevim.vim --force &
code --install-extension wart.ariake-dark --force &
code --install-extension wholroyd.jinja --force &
code --install-extension withfig.fig --force &
code --install-extension yzhang.markdown-all-in-one --force &
code --install-extension zhuangtongfa.material-theme --force
