#!/usr/bin/env zsh

# Check whether Terminal has Full Disk Access
if [[ ! -r "/Library/Application Support/com.apple.TCC/TCC.db" ]]; then
    echo "Full Disk Access must be granted to Terminal in order to run this script."
    open "x-apple.systempreferences:com.apple.preference.security?Privacy"
    exit
fi
