tap "buo/cask-upgrade"
tap "candid82/brew"
tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jason0x43/neovim-nightly"
tap "jez/formulae"
tap "romkatv/powerlevel10k"
tap "xwmx/taps"
tap "yqrashawn/goku"
# Library for command-line editing
brew "readline"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Core application library for C
brew "glib"
# GNOME accessibility toolkit
brew "atk"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU multiple precision arithmetic library
brew "gmp"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Bash Automated Testing System
brew "bats-core"
# Google's own build tool
brew "bazel"
# Garbage collector for C and C++
brew "bdw-gc"
# Collection of portable C++ source libraries
brew "boost"
# Freely available high-quality data compressor
brew "bzip2"
# Vector graphics library with cross-device output support
brew "cairo"
# Library for processing command-line flags
brew "gflags"
# Application-level logging library
brew "glog"
# Optimized BLAS library
brew "openblas"
# C++ library for large-scale optimization
brew "ceres-solver"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Compression/decompression library aiming for high speed
brew "snappy"
# Play, record, convert, and stream audio and video
brew "ffmpeg@4"
# File format designed to store large amounts of data
brew "hdf5"
# Key-value storage library with ordered mapping
brew "leveldb"
# Lightning memory-mapped database: key-value data store
brew "lmdb"
# Package for scientific computing with Python
brew "numpy"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Python bindings for v5 of Qt
brew "pyqt@5"
# Toolkit for 3D computer graphics, image processing, and visualization
brew "vtk"
# Open source computer vision library
brew "opencv"
# Fast open framework for deep learning
brew "caffe"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Modern replacement for 'ls'
brew "exa"
# Command-line tool to interact with exercism.io
brew "exercism"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Image manipulation
brew "netpbm"
# GNU triangulated surface library
brew "gts"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GSettings schemas for desktop components
brew "gsettings-desktop-schemas"
# GUI toolkit
brew "gtk+"
# Toolkit for creating graphical user interfaces
brew "gtk+3"
# Integrates GTK macOS applications with the Mac desktop
brew "gtk-mac-integration"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Command-line benchmarking tool
brew "hyperfine"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# C/C++ seam carving library
brew "liblqr"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Linear Algebra PACKage
brew "lapack"
# Implementations for atomic memory update operations
brew "libatomic_ops"
# I/O abstraction library for dealing with structured file formats
brew "libgsf"
# Implementation of the file(1) command
brew "libmagic"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# Show markdown documents on text terminals
brew "mdcat"
# Fast and user friendly build system
brew "meson"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# C library to read whole-slide images (a.k.a. virtual slides)
brew "openslide"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Render and include figures in Pandoc documents using many plotting toolkits
brew "pandoc-plot"
# Cross-platform application and UI framework
brew "qt"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Alternative to pyenv for managing virtualenvs
brew "pyenv-virtualenvwrapper"
# File browser
brew "ranger"
# Ruby version manager
brew "rbenv"
# Rsync for cloud storage
brew "rclone"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Rust toolchain installer
brew "rustup-init"
# Intuitive find & replace CLI
brew "sd"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Fuzzy Finder in rust!
brew "sk"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"
# Official documentation format of the GNU project
brew "texinfo"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Linear algebra library for many-core architectures and multi-core CPUs
brew "viennacl"
# Vi 'workalike' with many additional features
brew "vim"
# Image processing library
brew "vips"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# Access X11 clipboards from the command-line
brew "xclip"
# JavaScript package manager
brew "yarn"
# Tracks most-used directories to make cd smarter
brew "z"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# Task runner / simpler Make alternative written in Go
brew "go-task/tap/go-task"
brew "xwmx/taps/nb"
# karabiner configurator
brew "yqrashawn/goku/goku"
# Password manager that keeps all passwords secure behind one password
cask "1password-beta"
# Command-line helper for the 1Password password manager
cask "1password-cli-beta"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# Application uninstaller
cask "appcleaner"
# Data backup and storage service
cask "backblaze"
# 3D creation suite
cask "blender"
# Tool to show live information about the batteries in various devices
cask "coconutbattery"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Utility to finds and fix problems on computer systems
cask "etrecheckpro"
# Calendar software
cask "fantastical"
# Reimagine your terminal
cask "fig"
# Web browser
cask "firefox"
# Typeface made for developers
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
# Vector graphics editor
cask "inkscape"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Keyboard customizer
cask "karabiner-elements"
# Tool to show what is persistently installed on the computer
cask "knockknock"
# Software for Logitech devices
cask "logi-options-plus"
# Update your Logitech wireless receivers and selected keyboards
cask "logitech-firmwareupdatetool"
# Utility for pairing devices with Unifying receivers
cask "logitech-unifying"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Scanner app for math and science
cask "mathpix-snipping-tool"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Native app email client for Gmail
cask "mimestream"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# App to write, plan, collaborate, and get organized
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Desktop virtualization software
cask "parallels"
# Environment for statistical computing and graphics
cask "r"
# All-in-one bookmark manager
cask "raindropio"
# Control your tools with a few keystrokes
cask "raycast"
# Data science software focusing on R and Python
cask "rstudio"
# Collection of apps available by subscription
cask "setapp"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# File transfer application
cask "transmit"
# VPN client for secure internet access and private browsing
cask "tunnelbear"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Video communication and virtual meeting platform
cask "zoom"
mas "1Password for Safari", id: 1569813296
