#!/bin/bash
defaults write com.apple.Finder "AppleShowAllFiles" -bool "true"

# Hide Dock automatically
deaults write com.apple.dock autohide -bool true

# Fix battery indicator
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show file ext
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show directory first
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Do not make .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Set delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Set key repeat speed
defaults write NSGlobalDomain KeyRepeat -int 2

# Fix tap behavior
defaults write -g com.apple.mouse.tapBehavior -int 1

# Disable spotlight
mdutil -s / | grep enabled && sudo mdutil -i off /

killall Dock
killall Finder
killall SystemUIServerf
