#!/usr/bin/env bash

# Close any open System Preferences panes to prevent overriding
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing sudo timestamp until macos has finished
while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
done 2>/dev/null &

# Check whether Terminal has Full Disk Access
if [[ ! -r "/Library/Application Support/com.apple.TCC/TCC.db" ]]; then \
    echo "Full Disk Access must be granted to Terminal in order to run this script." \
    open "x-apple.systempreferences:com.apple.preference.security?Privacy" \
    exit \
fi

#show ~/Library
chflags nohidden ~/Library/

# Show the /Volumes folder
sudo chflags nohidden /Volumes

defaults write com.apple.Finder "AppleShowAllFiles" -bool "true"

# Hide Dock automatically
defaults write com.apple.dock autohide -bool true
# quick authoide
defaults write com.apple.Dock autohide-delay -float 0

# Fix battery indicator
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show file ext
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show directory first
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Do not make .DS_Store
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Set delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -float 10.0

# Set key repeat speed
defaults write NSGlobalDomain KeyRepeat -float 1.0

# Disable special characters
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Fix tap behavior
defaults write -g com.apple.mouse.tapBehavior -int 1

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Save to disk instead of iCloud
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari ShowDevelopMenu -bool true

# Add a context menu item for showing the Web Inspector in web views
defaults write -g WebKitDeveloperExtras -bool true

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

## APP STORE ##

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

## PHOTOS ##

# Prevent Photos from opening automatically when devices are plugged in
defaults write com.apple.ImageCapture disableHotPlug -bool true
killall Dock
killall Finder
