#!/usr/bin/env zsh
PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin"

# load environmental variables
source ~/.oh-my-zsh/custom/_paths.zsh

crontab -l > ${core}/scripts/crontab.save

chezmoi re-add ${core}/scripts/crontab.save

echo "crontab saved as ${core}/scripts/crontab.save"