name: Test Setup dotfiles on Mac OS

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Setup upterm session
        # uses: lhotari/action-upterm@v1
      - name: Run setup dotfiles
        run: |
          set -eo pipefail
          export CI=1
          TERM=xterm zsh init.sh
